server {
    listen       80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html;

    # Compressão gzip
    gzip on;
    gzip_types text/plain text/css application/javascript;
    gzip_min_length 256;

    # Cache para assets estáticos
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    # SPA fallback (garante que index.html é servido para qualquer rota)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Esconde versão do nginx
    server_tokens off;
}
